
version: "3.8"

volumes:
  pgdata:
    external: true

networks:
  default:
    name: webnet
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: always
    networks:
      - default
    hostname: ${DB_HOST}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  server:
    container_name: main
    build:
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - postgres